### ISSUE TITLE
Some feedbacks & questions

### ISSUE THREAD

**Issue by bitsnaps** [mogenius/docs#5]
Hi @janlepsky ,

I've just tried to contact you via the website, but the validation rule at the field `Interest` prevented me (no option value available, and the form requires a value), here is my question:

Hi, do you support Serverless functions? What makes you different form (or better than) Netlify/Vercel?

Also, the link to `Tell us your requirements` in the [pricing](https://mogenius.com/pricing) page, leads to typeform website not the actual form.

Other than that, the website is cool as well as the service, good luck.

Regards

**Comment by janlepsky** [comment]
Hi @bitsnaps,

Please excuse the bugs you experienced on our website and thanks a lot for letting us know. We'll fix this right away.

We don't support serverless functions yet but we already considered to implement it in the future. In short, our cloud platform is a highly scalable cloud infrastructure, made simple and accessible for every Dev from day one. While Netlify/Vercel are great for frontend applications, mogenius is designed to run whole microservice architectures (frontend, backend, databases, APIs etc.). With Kubernetes under the hood and Cloudflare integration it has also great capabilities in terms of scalability and security for tech teams. And we work with fixed pricing so there's no risk of exploding costs.

We highly appreciate your feedback! Let me know if you have any question. You can also contact me directly at jan(at)mogenius.com.

Best,
Jan
